server:
  port: 8099
mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/sys/article/**.xml
mybatis-plus:
  global-config:
    db-config:
      db-type: MYSQL
spring:
  datasource:
    name: datasource
    url:  jdbc:mysql://rm-2ze16py964xf52253co.mysql.rds.aliyuncs.com:3306/scale1?useUnicode=true&amp;characterEncoding=UTF-8
    #url: jdbc:mysql://localhost:3306/scale?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: TsRJKMKOnbJ#$
    #password: root
    tomcat:
      max-active: 5
      min-idle: 2
      max-idle: 5
      initial-size: 2
      test-on-borrow: true
      test-on-return: false
      max-wait: 3000
  aop:
    proxy-target-class: true
    auto: true
  servlet:
    multipart:
      max-file-size: 800MB
      max-request-size: 800MB

controller.scanPackage: com.edgedo.sys.controller
#rsa公钥
JwtRsaSecKey.rsaPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkR7i7tBvWop/3H32izJz/zCLxEG5Jv469h3G57hBWixq78zgmymqZxwmB+zFsXDd6gI+7769NYZUEsm9L9BHIGEIprOr2JtdMg8Ypxs7Niyq1sw7WcDXseK+w02QFuzaXQg6Df6j/NlxJ3d6mHGpQUfW298qDauh9HZu287SWUqjZWXeEW3nthfLtmBkH4tnG5U1qzu6xAvhoKgqpJQpFnfXlTCbWOy+LBQ2s3FqDIu8C9AM8+kfF2lbu3v/NTRG+UNi6f7Oxt6q8Yh6iDu1mFrow5X7S8aLGA6R3I7ElP24tnB56vIR0HI4lq2i6gNnlMyCPyWRVUDh0UkhxqpmdQIDAQAB
#rsa私钥
JwtRsaSecKey.rsaPrivateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCRHuLu0G9ain/cffaLMnP/MIvEQbkm/jr2HcbnuEFaLGrvzOCbKapnHCYH7MWxcN3qAj7vvr01hlQSyb0v0EcgYQims6vYm10yDxinGzs2LKrWzDtZwNex4r7DTZAW7NpdCDoN/qP82XEnd3qYcalBR9bb3yoNq6H0dm7bztJZSqNlZd4Rbee2F8u2YGQfi2cblTWrO7rEC+GgqCqklCkWd9eVMJtY7L4sFDazcWoMi7wL0Azz6R8XaVu7e/81NEb5Q2Lp/s7G3qrxiHqIO7WYWujDlftLxosYDpHcjsSU/bi2cHnq8hHQcjiWraLqA2eUzII/JZFVQOHRSSHGqmZ1AgMBAAECggEBAJEa6xqTu+QyfGsCYJUKm8XcysQwW2xL5LTXTV3BdUcvBrZEi4lafhKfqL9f1sT38EzedgPPGu38JPCsW8kFXzlXDQlyui/aGbPGOIZOykP/IcupZub11jb+XHR4h80Eg8tmQHZh2aMn4ObvptvrOqwVoxcy65/DsCr6iRqskNPKNltu1eCRduQzI0ygb1vTcVT0KqEKqe5UdvQfbc4ciwZkYkWWXr2NVt2UB2Vycm9ym7835/STsSXGNBNxjQnBWKjLAhNGKrbK4IfQehcmk9QjmK/1mLQmjus5Lri1h4JYPXpfU9+T02iFGa+H5DtaUe4Kpd2i1qRYrcXI9EjY3TkCgYEAw6tnHBm9A+bcgN2GC/gX72k1y56uGEN2WnB4f0sIfWs4+EqeJeLoEIO+5/pmXLv7rN7luigRgaaC8vFlS/qbwkysEIw5lNyrU1i4O352pT1ENTe73x425hdrtHkTSzt+3KcQd4iZ8wcNuJGOOtRF7GpR3acIIeFRm+oA3IauC4cCgYEAvd2OZgYh4v+MZT+1BUs/gVIzqXDUsTHvSgIqNUs8/LA1lGjYhsaAfCRBUUegjO+ovo8y+VNDJDyX1Rj67BifVmteIChPuyxFTLHd03Oe4HtAB7BErgM7Y/VUf5tkiJf6kyMNqjVfXfiHGKARdf7SZF+VT0/VCXpcGlXMIkVdVSMCgYEAnvkdduk6dncU4+YXSJYy7CKwwFSV4cS93dDPNazCoxOAX8pQHzvxi6lea583l1RrsBIQ12RChPHCJpwVzts3vW8JxRAIoHeBAuBsHnoq7ymNxycXDrm/pMWWjjRohpE6Cw/5AwUK/zbV4QTxZ76baO8gwFM6+jvUUDaYqJMLyPUCgYEArPs3apJ5uzPyeKijR1B4al03Pk/TKCGDjt0MEYQb62irWCxx4dDmbLQnYmMszlrnVb5nxaprSI+AEaFxszr3qKenmQrBIZnDBY4juSvk+0avXpHk8Nl2+aohsyUjYiN9IyLTp1h7K8VraC8l2WgxzUscYKcuRDVbxo6Wrj6eOxsCgYAiH0eK9lQsJ/Gi/IzFU57yu3tLxoYm9b3aWxlM/vxaEDRiLeji7q9B+gXpqzP19x7d4QWIjMNsFtqrPJWmRJJD1tI6f3wPz0r8Sjnwq+iTzZvrvXvWh+gtGfvkHSkne1dYv8oIPy6zWXeLwGbPpzMgO4WQOZX+PhqX2gLMx+pM3g==
#jwt token秘钥
JwtRsaSecKey.jwtSecretkey: 6a4c9416da35432ca5ff612ce88eb6de




